esphome:
  name: bruhsensoroffice
  platform: ESP8266
  board: d1_mini_lite

wifi:
  networks:
  - ssid: !secret wifissid
    password: !secret wifipassword
  - ssid: "telenet-2CF19B3"
    password: "w2cvmkwQwfex"
sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "Multisensor Temperature"
    humidity:
      name: "Multisensor Humidity"
    update_interval: 60s
    model: AM2302
#   - platform: adc
#     pin: A0
#     name: "Multisensor Brightness"
#     unit_of_measurement: lux
#     filters:
#       - lambda: |-
#           return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D6
    name: "Multisensor Motion"
    device_class: motion

remote_receiver:
  pin:
    number: D4
    inverted: True
  dump: all

remote_transmitter:
  pin: D8
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: Delonghi-PACEL98RF Power Button
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FFC13E
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Real Feel
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF41BE
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Mode
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF837C
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Down
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF01FE
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Up
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF21DE
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Fan
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x4004
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Timer
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF817E
          nbits: 32
  - platform: template
    name: Delonghi-PACEL98RF Silent
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0xF8FF619E
          nbits: 32


# output:
#   - platform: esp8266_pwm
#     pin: D5
#     id: redgpio
#   - platform: esp8266_pwm
#     pin: D6
#     id: greengpio
#   - platform: esp8266_pwm
#     pin: D7
#     id: bluegpio

# light:
#   - platform: rgb
#     name: "Multisensor Light"
#     red: redgpio
#     green: greengpio
#     blue: bluegpio

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
