esphome:
  name: smart-meter
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: false

logger:
  baud_rate: 0

ota:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  rx_pin:
    number: D3
    inverted: true
    mode:
      input: true
      pullup: true
  baud_rate: 115200
  rx_buffer_size: 1700

dsmr:
#  request_pin: D4
#  crc_check: false
  max_telegram_length: 1700

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "energy day"
    energy_delivered_tariff2:
      name: "energy night"
    power_delivered:
      name: "power"
    electricity_failures:
      name: "failures"
    electricity_long_failures:
      name: "failures long"
    voltage_l1:
      name: "voltage L1"
    current_l1:
      name: "current L1"
    power_delivered_l1:
      name: "power L1"
    gas_delivered_be:
      name: "gas"

  - platform: uptime
    name: "smart meter reader uptime"

text_sensor:
  - platform: dsmr
    identification:
      name: "smart_meter"
    p1_version_be:
      name: "DSMR V5 P1 BE"
    timestamp:
      name: "time"
    electricity_tariff:
      name: "tariff"
    electricity_failure_log:
      name: "failure log"
    message_short:
      name: "message short"
    message_long:
      name: "message long"
    gas_equipment_id:
      name: "gas ID"
    sub_equipment_id:
      name: "sub ID"
