esphome:
  name: sonoff_s20_tv
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifissid
  password: !secret wifipassword

api:

logger:

ota:

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff S20 Button"
  on_press:
    - light.toggle: s20_light
- platform: status
  name: "Sonoff S20 Status"


switch:
  - platform: restart
    name: "Sonoff S20 Restart"

output:
- platform: esp8266_pwm
  id: s20_green_led
  pin: GPIO13
  inverted: True
- platform: gpio
  id: s20_relay
  pin: GPIO12

light:
- platform: monochromatic
  name: "Sonoff S20 TV Green LED"
  output: s20_green_led
- platform: binary
  id: s20_light
  name: "Sonoff S20 TV"
  output: s20_relay
